name: Tests

# Test django-pipelines on:
#   all supported Django and Python versions

on:
  push:
  pull_request:

jobs:
  test:
    name: py-${{ matrix.python-version }} dj-${{ matrix.django-version }} django-pipelines
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
        django-version:
          - "3.2"
          - "4.0"
          - "4.1"
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        working-directory: .
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install "django~=${{ matrix.django-version }}.0"
      - name: Lint
        working-directory: .
        run: |
          flake8
      - name: Test
        working-directory: .
        run: |
          pytest -x
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          name: ${{ matrix.python-version }}-${{ matrix.django-version }}
